---
sidebar: sidebar 
permalink: task-view-storagegrid.html 
keywords: storagegrid, cluster, view, alerts, nodes, tenants, capacity, used capacity, free capacity, system ID, domain, IP, object data used, object metadata used, cpu usage, quota utilization, quota 
summary: Une fois que vous avez découvert vos systèmes StorageGRID , vous pouvez afficher les détails sur la distribution de la capacité et les alertes, nœuds et locataires associés. 
---
= Affichez vos systèmes StorageGRID
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Une fois que vous avez découvert vos systèmes StorageGRID , vous pouvez afficher les détails sur la distribution de la capacité et les alertes, nœuds et locataires associés.

.Rôle de NetApp Console requis :
Administrateur de stockage ou spécialiste de la santé du système.link:https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["En savoir plus sur les rôles d’accès à la NetApp Console ."^]

.Étapes
. Dans le menu de navigation, sélectionnez *Stockage > Gestion*.
. Sur la page *Systèmes*, sélectionnez le système StorageGRID que vous souhaitez afficher.
. Sélectionnez parmi les options de menu disponibles pour afficher plus de détails sur votre système StorageGRID :
+
** *Vue d'ensemble* : Une vue détaillée de la répartition de la capacité du système (capacité utilisée et libre), du nombre d'alertes système, de nœuds et de locataires, et bien plus encore.
** *Alertes* : un résumé des alertes système, qui comprend les alertes actives, les alertes résolues et les alertes désactivées.
** *Nœuds* : Détails sur le nœud d'administration, le nœud de passerelle API et les nœuds de stockage.  Cela inclut les pourcentages des données d'objet utilisées, des métadonnées d'objet utilisées et de l'utilisation du processeur.
** * Locataires * : détails clés sur les locataires, qui incluent l'espace logique utilisé, l'utilisation du quota, le quota et le nombre d'objets.



